# datasource config
spring:
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.169:3306/java-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=true
    username: root
    password: liuyunji

# logger config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug